### ISSUE TITLE
Tracking issue for improve TinyKV as a learning-friendly distributed key-value database

### ISSUE THREAD

**Issue by tisonkun** [talent-plan/tinykv#275]
It is corresponding to the effort towards [Talent Plan](https://learn.pingcap.com/learner/talent-plan/implement-a-mini-distributed-key-value-database) v3.0.

After an investigate I notice that the most terrible issues stop TinyKV as a learning-friendly distributed key-value database are these four directions:

1. Documents unfriendly. Its description fall through in sentences instead of show the aim and related files first, and later teach knowledge topics step by step.
2. Layout of code unmanaged. Code of project 1 and project 4 mixed; code of project 2 and project 3 mixed. Golang supports splitting code into files in one package arbitrary, and we should make use of that to rearrange our code. What's more, unrelated or copy-pasted code chunk should be squashed.
3. Poor comments, especially for to-be-implemented methods and other essential structures, interfaces, and functions.
4. Several chapters themselves can be redesigned, e.g., Scheduler and Transaction.

I plan to go throw the whole course project by project and fix these issues per project.

## Documents unfriendly

* [x] #276

Generally I propose a layout like below.

```markdown
## Overview

// brief background and aims

## Related Files

## Specification

## Validation

```

... also we can factor out unessential learning materials from the project description and leave only a link.

* [x] #282
* [ ] Rephrase project description of Raft KV
* [ ] Rephrase project description of Multi-Raft KV
* [ ] Rephrase project description of Transaction

## Layout of code unmanaged

* [x] #283
* [ ] Rearrange code of project2aa
* [ ] Rearrange code of project2ab
* [ ] Rearrange code of project2ac
* [ ] Rearrange code of project2b
* [ ] Rearrange code of project2c
* [ ] Rearrange code of project3a
* [ ] Rearrange code of project3b
* [ ] Rearrange code of project3c
* [ ] Rearrange code of project4a
* [ ] Rearrange code of project4b
* [ ] Rearrange code of project4c
* [x] #268

## Poor comments

These works can be done along with rearrange code.

## Several chapters themselves can be redesigned

* [ ] Substantially simplify scheduler section
* [ ] Implement transaction based on the former projects
* [ ] #273

**Comment by tisonkun** [comment]
Closed as no more activities.
